language: r
r: bioc-release
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- ./_build.sh
- ./_deploy.sh
sudo: true
cache:
  packages: true
  directories:
  - $TRAVIS_BUILD_DIR/_bookdown_files
apt_packages: libnetcdf-dev
env:
  global:
  - secure: sqrtxp9efTETl0I+q/tdZ9SdmC8AUUMABwKHoTfawmRAcKiUgO97ketmzMLD49M1ExIOXNx87YmqfvD7o/avRJ28L5tr7lms0LxdQyLzZf/vtvQm1yC/85g65Cq1B3k8ULoPNE9+2R+o8HblKU/qrtLLnh9aEtw+NrCQLAMhRbgC7ClyXYcd01ZLO9bvUhrU79Rk06e5x8wzVN6rmBcr2/OpRhAzwY+OoIT/YxqglNk3zRwVOyPoVBpOV8UdMYEjhpjAfUw4jA+cH1sk+hzWWb2MNUOcMCfNkzj/Og8qr/tw3JTeRiOPJRkH4Cb8iVtQjmrEYTD767zlTFivtjPU937BufMAGVECMccILA8I2IHNRfQzMlM25KZvvUlN7vXFEjTvglEbsJoX1H+RNfurlHxvPW9g1I+6SnMPPVhunP1YrIBv4Qascx0cqLv87QcABqAVHDNCDGZWLO0Tqh0dP69pF8ZQ0RVnXaIy6Q3XiWlpj10I1tf52L92qzLoal97UE1vthFPZziIEkCRNwMEqUFow1j18IgE2+qBdLojGlPWLbbzBQhieuI4PsYpf9xXUrLucxtQNNkAH2oS2RWFnI1eQF0OuK2FWKq5nHhIsK9GePfGGOwRMFSD1o9zHcs6fuBtPlDtkDa75YqWmw2JOykt2QIRRfJgF0jo+7xF0l4=
dd:
  secure: gMT4qEdGoogON/GVYXlzxCdURevwnudoHAk4Uxz3hHMwYurkzSk/JuE20pNrDfbd/RQaj+7Ibw4y+mRLVoTg+AfZAelafx8t7pqxW70jr8+6W8p/XtFpowWF1FpKY8LpWZUX9+aFvC1A+gMY2xSrqTHoR4sx1J5uAIZW85yiXPpw7sR72oU6tKaRY13lDD47mMpkNNYy3Hg9/ToY4eQzhYrRG62+7inR3LFpY1IUtybwK0iHE2iIdgRZXUIbt5JbImYNUMDoDHVSxewF58Qy0RuXzYm3WeSGbTTxGjaYbdvq44z8vJfsIvsifym+MVIS3SXs0cyrHrUQwHu0cNdqYF/7F/JdJ6MjmEfg9UoMtjh2LIOtKyFADCA9I70Ae1B1M706Am4th8HkcmJ0f691tH6xtIQKELg7joS9/Y1fx51tbrmqSRwVIMzBTHxcFFS4YEUae6ynGSM7cCF1YMJQ80ksY9I6vgtNic3jUPtW3UjqdCcQbN+kfpCvDRr/bXNAnNxS+1XmyNoEE4MxxSLrMU4WxjuYRHBe0lr2Jm/NCAI6Xrhrr2l/0g1QR32RtHi0liPl++gxO/aZOxYGvfC+9Lj+lBo5VN3y1569Vy1hHZDDqczythAKPzTD0G19dr3DYyCCYBJCQbOeZTJVV1HL5XW9s5swraI2VHqe0iZpZ60=
